# Exploratory Data Analysis (EDA)

This notebook performs basic exploratory data analysis on a given dataset using Python and Pandas.

In [4]:
## 1. Importing Required Libraries
import pandas as pd
import numpy as np
import matploistlib.pyplot as plt

In [6]:
## 2. Loading the Dataset
df=pd.read_csv("/content/50_Startups.csv")

In [7]:
## 3. Displaying First Few Rows
df.head(2)

,Unnamed: 0,R&D Spend,Administration,Marketing Spend,State,Profit
0,0,165349.3,136897.90,471784.20,New York,192261.93
1,1,162597.8,151377.69,443898.63,California,191792.16

In [8]:
## 4. Checking Dataset Shape
df.shape

(50, 6)

In [9]:
## 5. Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       50 non-null     int64
 1   R&D Spend        50 non-null     float64
 2   Administration   50 non-null     float64
 3   Marketing Spend  50 non-null     float64
 4   State            50 non-null     object
 5   Profit           50 non-null     float64
dtypes: float64(4), int64(1), object(1)
memory usage: 2.5+ KB

In [10]:
## 6. Checking Missing Values
df.isnull().sum()

Unnamed: 0         0
R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [11]:
## 7. Statistical Summary
df.describe()

,Unnamed: 0,R&D Spend,Administration,Marketing Spend,Profit
count,50.00000,50.000000,50.000000,50.000000,50.000000
mean,24.50000,73721.715600,121344.739600,211025.197800,112012.739200
std,14.57738,45902.256482,28017.802755,122290.310726,40306.180338
min,0.00000,0.100000,51283.240000,0.100000,14681.500000
25%,12.25000,39936.470000,103730.975000,129300.232500,90139.002500
50%,24.50000,73051.180000,122699.895000,212716.340000,107978.290000
75%,36.75000,101602.900000,144842.280000,299469.185000,139766.077500
max,49.00000,165349.300000,182645.660000,471784.200000,192261.930000

In [ ]:
## 8. Checking Frequency of Each State
df["State"].value_counts()

State
New York      17
California    17
Florida       16
Name: count, dtype: int64

In [ ]:
## 9. Creating a State Encoding Dictionary

state_dict = {
    "California": 0,
    "New York": 1,
    "Florida": 2
}

In [ ]:
## 10. Converting State Names into Numerical Values
df["State_num"] = df["State"].map(state_dict)
df["State_num"]

0     1
1     0
2     2
3     1
4     2
5     1
6     0
7     2
8     1
9     0
10    2
11    0
12    2
13    0
14    2
15    1
16    0
17    1
18    2
19    1
20    0
21    1
22    2
23    2
24    1
25    0
26    2
27    1
28    2
29    1
30    2
31    1
32    0
33    2
34    0
35    1
36    2
37    0
38    1
39    0
40    0
41    2
42    0
43    1
44    0
45    1
46    2
47    0
48    1
49    0
Name: State_num, dtype: int64

In [ ]:
## This step separates the independent variables (X) by dropping Profit and
## State columns and sets Profit as the dependent variable (y).
x = df.drop(["Profit", "State"], axis=1)
y = df["Profit"]

In [ ]:
## Checking Shape of X and Y
print("shape of x", x.shape)
print("shape of y", y.shape)

shape of x (50, 5)
shape of y (50,)

In [ ]:
## Importing Train-Test Split Function
from sklearn.model_selection import train_test_split

In [ ]:
## Splitting Data into Training and Testing Sets
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=0)

In [ ]:
## Checking Shape of Training and Testing Dataprint("shape of x_train: ",x_train.shape)
print("shape of x_test: ",x_test.shape)

shape of x_train:  (40, 5)
shape of x_test:  (10, 5)

In [ ]:
## Checking Shape of Training and Testing Labels
print("shape of y_train: ",y_train.shape)
print("shape of y_test: ",y_test.shape)

shape of y_train:  (40,)
shape of y_test:  (10,)

In [ ]:
## Importing Linear Regression Model
from sklearn.linear_model import LinearRegression

In [ ]:
lr = LinearRegression()

In [ ]:
## Training the Linear Regression Model
lr.fit(x_train, y_train)

LinearRegression()

In [ ]:
## Importing Model Evaluation Metrics
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [ ]:
## Displaying Predicted Values
y_pred=lr.predict(x_test)
y_pred

array([101225.28920045, 140881.9317955 , 140970.03836198,  69666.74992093,
       176730.93678837, 111384.86796512,  71391.07782783,  95035.15400541,
       116476.57420621, 168399.87364113])

In [ ]:
#MAE
print("MAE value: " , mean_absolute_error(y_test,y_pred))

MAE value:  6003.760791201443

In [ ]:
#MSE
print("MSE value: ",  mean_squared_error(y_test,y_pred))

MSE value:  49920577.069633745

In [ ]:
#RMSE
print("RMSE value: ",  np.sqrt(mean_squared_error(y_test,y_pred)))

RMSE value:  7065.4495306125955

In [ ]:
## Calculating R² Score
print("R2 Score: ",r2_score(y_test,y_pred))

R2 Score:  0.9609657477281474